apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: nandadocker23/my-python-app:40a19087783f219970a06ec7df7536c5179225e7
        imagePullPolicy: Always