apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: nandadocker23/my-python-app:b1fa8f0637d7fbfd77786eb94eb2cbfedff89189
        imagePullPolicy: Always