apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: nandadocker23/my-python-app:123af2d66672d073133646a05eedcc65f5560111
        imagePullPolicy: Always