apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: nandadocker23/my-python-app:1fa535571db18b069564f9a0f65c24331628e30b
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

        livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20