apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  COMPANY: {{ .Values.env.COMPANY | quote }}
  NAMESPACE: {{ .Values.env.NAMESPACE | quote }}
