apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  revisionHistoryLimit: 5

  progressDeadlineSeconds: 600

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      {{- include "flask-chart.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "flask-chart.selectorLabels" . | nindent 8 }}

    spec:

      serviceAccountName: {{ .Values.serviceAccount.name }}
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      terminationGracePeriodSeconds: 30

      containers:

      - name: flask

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 10

        ports:
        - name: http
          containerPort: 5000
          protocol: TCP


        envFrom:

        - configMapRef:
            name: flask-config

        - secretRef:
            name: flask-secret
        
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3


        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3


        resources:
          {{- toYaml .Values.resources | nindent 10 }}
