apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  revisionHistoryLimit: 5

  progressDeadlineSeconds: 600

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      {{- include "flask-chart.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "flask-chart.selectorLabels" . | nindent 8 }}

    spec:

      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 30

      containers:

      - name: flask

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 10

        ports:
          - name: http
            containerPort: {{ .Values.container.port }}
            protocol: TCP


        envFrom:

        - configMapRef:
            name: flask-config

        - secretRef:
            name: flask-secret
        
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 12 }}

        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}

        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
