apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flask-chart.fullname" . }}-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "flask-chart.selectorLabels" . | nindent 6 }}