apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "flask-chart.fullname" . }}-alerts
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
    release: monitoring

spec:
  groups:
    - name: flask-application.rules
      rules:

        - alert: FlaskApplicationUnavailable
          expr: |
            kube_deployment_status_replicas_available{
              namespace="{{ .Release.Namespace }}",
              deployment="{{ include "flask-chart.fullname" . }}"
            } < 1
          for: 1m

          labels:
            severity: critical
            team: platform

          annotations:
            summary: "Flask application is unavailable"
            description: "No available replicas for {{ include "flask-chart.fullname" . }} in namespace {{ .Release.Namespace }}."