{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "flask-chart.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
