apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: my-python-app:autoscaling/HorizontalPodAutoscaler:dev/flask-hpa
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"my-python-app:autoscaling/HorizontalPodAutoscaler:dev/flask-hpa"},"name":"flask-hpa","namespace":"dev"},"spec":{"maxReplicas":10,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":70,"type":"Utilization"}},"type":"Resource"}],"minReplicas":3,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"flask-deployment"}}}
  creationTimestamp: "2026-07-11T15:07:12Z"
  name: flask-hpa
  namespace: dev
  resourceVersion: "160402"
  uid: 7f82958c-18f6-4d5c-9937-01837932c3bd
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-deployment
status:
  conditions:
  - lastTransitionTime: "2026-07-14T01:50:08Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-07-14T01:45:53Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-07-14T01:40:38Z"
    message: the desired replica count is less than the minimum replica count
    reason: TooFewReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 1
        averageValue: 1m
      name: cpu
    type: Resource
  currentReplicas: 3
  desiredReplicas: 3
  lastScaleTime: "2026-07-14T01:40:23Z"
