apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: my-python-app:/Service:dev/flask-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"my-python-app:/Service:dev/flask-service"},"name":"flask-service","namespace":"dev"},"spec":{"ports":[{"port":80,"targetPort":5000}],"selector":{"app":"flask"},"type":"NodePort"}}
  creationTimestamp: "2026-07-10T16:39:48Z"
  name: flask-service
  namespace: dev
  resourceVersion: "83768"
  uid: 92dcd14d-ee12-4d32-821e-def42c88bf9b
spec:
  clusterIP: 10.96.32.223
  clusterIPs:
  - 10.96.32.223
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31915
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
