name: Build and Push Docker Image to ECR

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: watchtower
  ECR_REGISTRY: 405804178912.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4. Run automated tests
      - name: Run pytest
        run: |
          python -m pytest -v

      # 5. Authenticate to AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::405804178912:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      # 6. Verify AWS identity
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      # 7. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 8. Set image tag
      - name: Set image tag
        run: |
          echo "IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      # 9. Build Docker image
      - name: Build Docker image
        run: |
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .

      # 10. Push Docker image to ECR
      - name: Push Docker image
        run: |
          echo "Pushing image: $IMAGE"
          docker push "$IMAGE"

      # 11. Update Helm image tag
      - name: Update Helm image tag
        run: |
          echo "Updating Helm values.yaml"

          sed -i "s|tag: .*|tag: ${GITHUB_SHA}|g" flask-chart/values.yaml

          cat flask-chart/values.yaml

      # 12. Commit Helm change
      - name: Commit Helm update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add flask-chart/values.yaml

          git commit -m "Update image tag to ${GITHUB_SHA}" || echo "No changes"

          git push