name: CI/CD Pipeline Git Push --> Docker --> Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 4. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:v2 .
      
      # 5. Push Image
      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:v2
      
      # 6. Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          echo "Applying Kubernetes manifests...."
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment flask-deployment
          